source 'https://rubygems.org'

gem 'rails', '~> 5.0.2'
gem 'puma', '~> 4.3'
gem 'sidekiq'

gem 'determinator', path: '../..'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'dotenv-rails'
end

group :development do
end
